name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8
      - name: Run flake8
        run: |
          flake8 lambda_csv.py lambda_html.py tests/

  test:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest boto3 beautifulsoup4 requests
      - name: Run tests
        run: |
          PYTHONPATH=. pytest -v

  deploy:
    runs-on: ubuntu-latest
    needs: test
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install awscli requests beautifulsoup4
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}  # Añadido para credenciales temporales
          aws-region: us-east-1
      - name: Package Lambda functions with dependencies
        run: |
          mkdir -p lambda_deps
          pip install requests beautifulsoup4 -t lambda_deps
          cp lambda_csv.py lambda_deps/
          cp lambda_html.py lambda_deps/
          cd lambda_deps
          zip -r ../lambda_csv.zip .
          mv lambda_csv.py lambda_html.py .
          zip -r ../lambda_html.zip .
          cd ..
      - name: Deploy lambda_csv to AWS Lambda
        run: |
          aws lambda update-function-code \
            --function-name process-html-lambda \
            --zip-file fileb://lambda_csv.zip
      - name: Deploy lambda_html to AWS Lambda
        run: |
          aws lambda update-function-code \
            --function-name download-pages-lambda \
            --zip-file fileb://lambda_html.zip
            